# Generated by Django 4.2.1 on 2023-06-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_message_save_message_unlikes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='save',
            new_name='saveMsg',
        ),
    ]
