# Generated by Django 4.2.1 on 2023-06-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0007_alter_message_likes_alter_message_savemsg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='saveMsg',
        ),
        migrations.RemoveField(
            model_name='message',
            name='unLikes',
        ),
    ]
